CREATE TABLE pullups (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    count INTEGER NOT NULL,
    record_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE squats (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    count INTEGER NOT NULL,
    record_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE pushups (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    count INTEGER NOT NULL,
    record_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE situps (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    count INTEGER NOT NULL,
    record_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE jumping_jacks (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    count INTEGER NOT NULL,
    record_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
